# Generated by Django 3.2.5 on 2021-07-29 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_homepageartcile_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageartcile',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 29, 20, 57, 24, 163192)),
        ),
        migrations.AlterField(
            model_name='homepageartcile',
            name='image_url',
            field=models.URLField(),
        ),
    ]
