# Generated by Django 3.2.5 on 2021-08-03 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_auto_20210803_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecarousel',
            name='carousel_item',
        ),
        migrations.AddField(
            model_name='homepageartcile',
            name='carousel_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='homepageartcile',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 22, 16, 38, 26762)),
        ),
    ]
