# Generated by Django 3.2.5 on 2021-08-03 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_auto_20210803_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageartcile',
            name='carousel_item',
        ),
        migrations.AlterField(
            model_name='homepageartcile',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 22, 17, 56, 779409)),
        ),
    ]
