# Generated by Django 3.2.5 on 2021-08-03 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0031_auto_20210803_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepageartcile',
            options={'ordering': ['date_time']},
        ),
        migrations.AddField(
            model_name='homepageartcile',
            name='trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='homepageartcile',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 23, 35, 25, 823004)),
        ),
    ]
