# Generated by Django 3.2.5 on 2021-08-03 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0032_auto_20210803_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageartcile',
            name='trending',
        ),
        migrations.AlterField(
            model_name='homepageartcile',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 23, 40, 9, 681870)),
        ),
    ]
